/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as appStockMovementsRouteImport } from './routes/(app)/stock-movements'
import { Route as appReportsRouteImport } from './routes/(app)/reports'
import { Route as appInventoryRouteImport } from './routes/(app)/Inventory'
import { Route as appDashboardRouteImport } from './routes/(app)/Dashboard'
import { Route as adminStaffRouteImport } from './routes/(admin)/staff'
import { Route as adminCategoriesRouteImport } from './routes/(admin)/categories'
import { Route as adminBranchesRouteImport } from './routes/(admin)/branches'
import { Route as appProductsIndexRouteImport } from './routes/(app)/products/index'
import { Route as appProductsProductIdRouteImport } from './routes/(app)/products/$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const appStockMovementsRoute = appStockMovementsRouteImport.update({
  id: '/(app)/stock-movements',
  path: '/stock-movements',
  getParentRoute: () => rootRouteImport,
} as any)
const appReportsRoute = appReportsRouteImport.update({
  id: '/(app)/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const appInventoryRoute = appInventoryRouteImport.update({
  id: '/(app)/Inventory',
  path: '/Inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const appDashboardRoute = appDashboardRouteImport.update({
  id: '/(app)/Dashboard',
  path: '/Dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const adminStaffRoute = adminStaffRouteImport.update({
  id: '/(admin)/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const adminCategoriesRoute = adminCategoriesRouteImport.update({
  id: '/(admin)/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const adminBranchesRoute = adminBranchesRouteImport.update({
  id: '/(admin)/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const appProductsIndexRoute = appProductsIndexRouteImport.update({
  id: '/(app)/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const appProductsProductIdRoute = appProductsProductIdRouteImport.update({
  id: '/(app)/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/branches': typeof adminBranchesRoute
  '/categories': typeof adminCategoriesRoute
  '/staff': typeof adminStaffRoute
  '/Dashboard': typeof appDashboardRoute
  '/Inventory': typeof appInventoryRoute
  '/reports': typeof appReportsRoute
  '/stock-movements': typeof appStockMovementsRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/products/$productId': typeof appProductsProductIdRoute
  '/products': typeof appProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/branches': typeof adminBranchesRoute
  '/categories': typeof adminCategoriesRoute
  '/staff': typeof adminStaffRoute
  '/Dashboard': typeof appDashboardRoute
  '/Inventory': typeof appInventoryRoute
  '/reports': typeof appReportsRoute
  '/stock-movements': typeof appStockMovementsRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/products/$productId': typeof appProductsProductIdRoute
  '/products': typeof appProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(admin)/branches': typeof adminBranchesRoute
  '/(admin)/categories': typeof adminCategoriesRoute
  '/(admin)/staff': typeof adminStaffRoute
  '/(app)/Dashboard': typeof appDashboardRoute
  '/(app)/Inventory': typeof appInventoryRoute
  '/(app)/reports': typeof appReportsRoute
  '/(app)/stock-movements': typeof appStockMovementsRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(app)/products/$productId': typeof appProductsProductIdRoute
  '/(app)/products/': typeof appProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/branches'
    | '/categories'
    | '/staff'
    | '/Dashboard'
    | '/Inventory'
    | '/reports'
    | '/stock-movements'
    | '/login'
    | '/signup'
    | '/products/$productId'
    | '/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/branches'
    | '/categories'
    | '/staff'
    | '/Dashboard'
    | '/Inventory'
    | '/reports'
    | '/stock-movements'
    | '/login'
    | '/signup'
    | '/products/$productId'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/(admin)/branches'
    | '/(admin)/categories'
    | '/(admin)/staff'
    | '/(app)/Dashboard'
    | '/(app)/Inventory'
    | '/(app)/reports'
    | '/(app)/stock-movements'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/(app)/products/$productId'
    | '/(app)/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  adminBranchesRoute: typeof adminBranchesRoute
  adminCategoriesRoute: typeof adminCategoriesRoute
  adminStaffRoute: typeof adminStaffRoute
  appDashboardRoute: typeof appDashboardRoute
  appInventoryRoute: typeof appInventoryRoute
  appReportsRoute: typeof appReportsRoute
  appStockMovementsRoute: typeof appStockMovementsRoute
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
  appProductsProductIdRoute: typeof appProductsProductIdRoute
  appProductsIndexRoute: typeof appProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/stock-movements': {
      id: '/(app)/stock-movements'
      path: '/stock-movements'
      fullPath: '/stock-movements'
      preLoaderRoute: typeof appStockMovementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/reports': {
      id: '/(app)/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof appReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/Inventory': {
      id: '/(app)/Inventory'
      path: '/Inventory'
      fullPath: '/Inventory'
      preLoaderRoute: typeof appInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/Dashboard': {
      id: '/(app)/Dashboard'
      path: '/Dashboard'
      fullPath: '/Dashboard'
      preLoaderRoute: typeof appDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/staff': {
      id: '/(admin)/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof adminStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/categories': {
      id: '/(admin)/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof adminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/branches': {
      id: '/(admin)/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof adminBranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/products/': {
      id: '/(app)/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof appProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/products/$productId': {
      id: '/(app)/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof appProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  adminBranchesRoute: adminBranchesRoute,
  adminCategoriesRoute: adminCategoriesRoute,
  adminStaffRoute: adminStaffRoute,
  appDashboardRoute: appDashboardRoute,
  appInventoryRoute: appInventoryRoute,
  appReportsRoute: appReportsRoute,
  appStockMovementsRoute: appStockMovementsRoute,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
  appProductsProductIdRoute: appProductsProductIdRoute,
  appProductsIndexRoute: appProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
