/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as appTransfersRouteImport } from './routes/(app)/transfers'
import { Route as appSuppliersRouteImport } from './routes/(app)/suppliers'
import { Route as appStockMovementsRouteImport } from './routes/(app)/stock-movements'
import { Route as appReportsRouteImport } from './routes/(app)/reports'
import { Route as appInventoryRouteImport } from './routes/(app)/inventory'
import { Route as appDashboardRouteImport } from './routes/(app)/dashboard'
import { Route as adminStaffRouteImport } from './routes/(admin)/staff'
import { Route as adminCategoriesRouteImport } from './routes/(admin)/categories'
import { Route as adminBranchesRouteImport } from './routes/(admin)/branches'
import { Route as appPurchaseOrdersIndexRouteImport } from './routes/(app)/purchase-orders/index'
import { Route as appProductsIndexRouteImport } from './routes/(app)/products/index'
import { Route as appPurchaseOrdersOrderIdRouteImport } from './routes/(app)/purchase-orders/$orderId'
import { Route as appProductsProductIdRouteImport } from './routes/(app)/products/$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const appTransfersRoute = appTransfersRouteImport.update({
  id: '/(app)/transfers',
  path: '/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const appSuppliersRoute = appSuppliersRouteImport.update({
  id: '/(app)/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const appStockMovementsRoute = appStockMovementsRouteImport.update({
  id: '/(app)/stock-movements',
  path: '/stock-movements',
  getParentRoute: () => rootRouteImport,
} as any)
const appReportsRoute = appReportsRouteImport.update({
  id: '/(app)/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const appInventoryRoute = appInventoryRouteImport.update({
  id: '/(app)/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const appDashboardRoute = appDashboardRouteImport.update({
  id: '/(app)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const adminStaffRoute = adminStaffRouteImport.update({
  id: '/(admin)/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const adminCategoriesRoute = adminCategoriesRouteImport.update({
  id: '/(admin)/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const adminBranchesRoute = adminBranchesRouteImport.update({
  id: '/(admin)/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const appPurchaseOrdersIndexRoute = appPurchaseOrdersIndexRouteImport.update({
  id: '/(app)/purchase-orders/',
  path: '/purchase-orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const appProductsIndexRoute = appProductsIndexRouteImport.update({
  id: '/(app)/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const appPurchaseOrdersOrderIdRoute =
  appPurchaseOrdersOrderIdRouteImport.update({
    id: '/(app)/purchase-orders/$orderId',
    path: '/purchase-orders/$orderId',
    getParentRoute: () => rootRouteImport,
  } as any)
const appProductsProductIdRoute = appProductsProductIdRouteImport.update({
  id: '/(app)/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/branches': typeof adminBranchesRoute
  '/categories': typeof adminCategoriesRoute
  '/staff': typeof adminStaffRoute
  '/dashboard': typeof appDashboardRoute
  '/inventory': typeof appInventoryRoute
  '/reports': typeof appReportsRoute
  '/stock-movements': typeof appStockMovementsRoute
  '/suppliers': typeof appSuppliersRoute
  '/transfers': typeof appTransfersRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/products/$productId': typeof appProductsProductIdRoute
  '/purchase-orders/$orderId': typeof appPurchaseOrdersOrderIdRoute
  '/products/': typeof appProductsIndexRoute
  '/purchase-orders/': typeof appPurchaseOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/branches': typeof adminBranchesRoute
  '/categories': typeof adminCategoriesRoute
  '/staff': typeof adminStaffRoute
  '/dashboard': typeof appDashboardRoute
  '/inventory': typeof appInventoryRoute
  '/reports': typeof appReportsRoute
  '/stock-movements': typeof appStockMovementsRoute
  '/suppliers': typeof appSuppliersRoute
  '/transfers': typeof appTransfersRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/products/$productId': typeof appProductsProductIdRoute
  '/purchase-orders/$orderId': typeof appPurchaseOrdersOrderIdRoute
  '/products': typeof appProductsIndexRoute
  '/purchase-orders': typeof appPurchaseOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(admin)/branches': typeof adminBranchesRoute
  '/(admin)/categories': typeof adminCategoriesRoute
  '/(admin)/staff': typeof adminStaffRoute
  '/(app)/dashboard': typeof appDashboardRoute
  '/(app)/inventory': typeof appInventoryRoute
  '/(app)/reports': typeof appReportsRoute
  '/(app)/stock-movements': typeof appStockMovementsRoute
  '/(app)/suppliers': typeof appSuppliersRoute
  '/(app)/transfers': typeof appTransfersRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(app)/products/$productId': typeof appProductsProductIdRoute
  '/(app)/purchase-orders/$orderId': typeof appPurchaseOrdersOrderIdRoute
  '/(app)/products/': typeof appProductsIndexRoute
  '/(app)/purchase-orders/': typeof appPurchaseOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/branches'
    | '/categories'
    | '/staff'
    | '/dashboard'
    | '/inventory'
    | '/reports'
    | '/stock-movements'
    | '/suppliers'
    | '/transfers'
    | '/login'
    | '/signup'
    | '/products/$productId'
    | '/purchase-orders/$orderId'
    | '/products/'
    | '/purchase-orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/branches'
    | '/categories'
    | '/staff'
    | '/dashboard'
    | '/inventory'
    | '/reports'
    | '/stock-movements'
    | '/suppliers'
    | '/transfers'
    | '/login'
    | '/signup'
    | '/products/$productId'
    | '/purchase-orders/$orderId'
    | '/products'
    | '/purchase-orders'
  id:
    | '__root__'
    | '/'
    | '/(admin)/branches'
    | '/(admin)/categories'
    | '/(admin)/staff'
    | '/(app)/dashboard'
    | '/(app)/inventory'
    | '/(app)/reports'
    | '/(app)/stock-movements'
    | '/(app)/suppliers'
    | '/(app)/transfers'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/(app)/products/$productId'
    | '/(app)/purchase-orders/$orderId'
    | '/(app)/products/'
    | '/(app)/purchase-orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  adminBranchesRoute: typeof adminBranchesRoute
  adminCategoriesRoute: typeof adminCategoriesRoute
  adminStaffRoute: typeof adminStaffRoute
  appDashboardRoute: typeof appDashboardRoute
  appInventoryRoute: typeof appInventoryRoute
  appReportsRoute: typeof appReportsRoute
  appStockMovementsRoute: typeof appStockMovementsRoute
  appSuppliersRoute: typeof appSuppliersRoute
  appTransfersRoute: typeof appTransfersRoute
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
  appProductsProductIdRoute: typeof appProductsProductIdRoute
  appPurchaseOrdersOrderIdRoute: typeof appPurchaseOrdersOrderIdRoute
  appProductsIndexRoute: typeof appProductsIndexRoute
  appPurchaseOrdersIndexRoute: typeof appPurchaseOrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/transfers': {
      id: '/(app)/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof appTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/suppliers': {
      id: '/(app)/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof appSuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/stock-movements': {
      id: '/(app)/stock-movements'
      path: '/stock-movements'
      fullPath: '/stock-movements'
      preLoaderRoute: typeof appStockMovementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/reports': {
      id: '/(app)/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof appReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/inventory': {
      id: '/(app)/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof appInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/dashboard': {
      id: '/(app)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/staff': {
      id: '/(admin)/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof adminStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/categories': {
      id: '/(admin)/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof adminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/branches': {
      id: '/(admin)/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof adminBranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/purchase-orders/': {
      id: '/(app)/purchase-orders/'
      path: '/purchase-orders'
      fullPath: '/purchase-orders/'
      preLoaderRoute: typeof appPurchaseOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/products/': {
      id: '/(app)/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof appProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/purchase-orders/$orderId': {
      id: '/(app)/purchase-orders/$orderId'
      path: '/purchase-orders/$orderId'
      fullPath: '/purchase-orders/$orderId'
      preLoaderRoute: typeof appPurchaseOrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/products/$productId': {
      id: '/(app)/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof appProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  adminBranchesRoute: adminBranchesRoute,
  adminCategoriesRoute: adminCategoriesRoute,
  adminStaffRoute: adminStaffRoute,
  appDashboardRoute: appDashboardRoute,
  appInventoryRoute: appInventoryRoute,
  appReportsRoute: appReportsRoute,
  appStockMovementsRoute: appStockMovementsRoute,
  appSuppliersRoute: appSuppliersRoute,
  appTransfersRoute: appTransfersRoute,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
  appProductsProductIdRoute: appProductsProductIdRoute,
  appPurchaseOrdersOrderIdRoute: appPurchaseOrdersOrderIdRoute,
  appProductsIndexRoute: appProductsIndexRoute,
  appPurchaseOrdersIndexRoute: appPurchaseOrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
