/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as appStockMovementsRouteImport } from './routes/(app)/stock-movements'
import { Route as appReportsRouteImport } from './routes/(app)/reports'
import { Route as appInventoryRouteImport } from './routes/(app)/inventory'
import { Route as appDashboardRouteImport } from './routes/(app)/dashboard'
import { Route as adminStaffRouteImport } from './routes/(admin)/staff'
import { Route as adminCategoriesRouteImport } from './routes/(admin)/categories'
import { Route as adminBranchesRouteImport } from './routes/(admin)/branches'
import { Route as appProductsRouteRouteImport } from './routes/(app)/products/route'
import { Route as appProductsIdRouteImport } from './routes/(app)/products/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const appStockMovementsRoute = appStockMovementsRouteImport.update({
  id: '/(app)/stock-movements',
  path: '/stock-movements',
  getParentRoute: () => rootRouteImport,
} as any)
const appReportsRoute = appReportsRouteImport.update({
  id: '/(app)/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const appInventoryRoute = appInventoryRouteImport.update({
  id: '/(app)/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const appDashboardRoute = appDashboardRouteImport.update({
  id: '/(app)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const adminStaffRoute = adminStaffRouteImport.update({
  id: '/(admin)/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const adminCategoriesRoute = adminCategoriesRouteImport.update({
  id: '/(admin)/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const adminBranchesRoute = adminBranchesRouteImport.update({
  id: '/(admin)/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const appProductsRouteRoute = appProductsRouteRouteImport.update({
  id: '/(app)/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const appProductsIdRoute = appProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => appProductsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/products': typeof appProductsRouteRouteWithChildren
  '/branches': typeof adminBranchesRoute
  '/categories': typeof adminCategoriesRoute
  '/staff': typeof adminStaffRoute
  '/dashboard': typeof appDashboardRoute
  '/inventory': typeof appInventoryRoute
  '/reports': typeof appReportsRoute
  '/stock-movements': typeof appStockMovementsRoute
  '/login': typeof authLoginRoute
  '/products/$id': typeof appProductsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/products': typeof appProductsRouteRouteWithChildren
  '/branches': typeof adminBranchesRoute
  '/categories': typeof adminCategoriesRoute
  '/staff': typeof adminStaffRoute
  '/dashboard': typeof appDashboardRoute
  '/inventory': typeof appInventoryRoute
  '/reports': typeof appReportsRoute
  '/stock-movements': typeof appStockMovementsRoute
  '/login': typeof authLoginRoute
  '/products/$id': typeof appProductsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)/products': typeof appProductsRouteRouteWithChildren
  '/(admin)/branches': typeof adminBranchesRoute
  '/(admin)/categories': typeof adminCategoriesRoute
  '/(admin)/staff': typeof adminStaffRoute
  '/(app)/dashboard': typeof appDashboardRoute
  '/(app)/inventory': typeof appInventoryRoute
  '/(app)/reports': typeof appReportsRoute
  '/(app)/stock-movements': typeof appStockMovementsRoute
  '/(auth)/login': typeof authLoginRoute
  '/(app)/products/$id': typeof appProductsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/products'
    | '/branches'
    | '/categories'
    | '/staff'
    | '/dashboard'
    | '/inventory'
    | '/reports'
    | '/stock-movements'
    | '/login'
    | '/products/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/products'
    | '/branches'
    | '/categories'
    | '/staff'
    | '/dashboard'
    | '/inventory'
    | '/reports'
    | '/stock-movements'
    | '/login'
    | '/products/$id'
  id:
    | '__root__'
    | '/'
    | '/(app)/products'
    | '/(admin)/branches'
    | '/(admin)/categories'
    | '/(admin)/staff'
    | '/(app)/dashboard'
    | '/(app)/inventory'
    | '/(app)/reports'
    | '/(app)/stock-movements'
    | '/(auth)/login'
    | '/(app)/products/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appProductsRouteRoute: typeof appProductsRouteRouteWithChildren
  adminBranchesRoute: typeof adminBranchesRoute
  adminCategoriesRoute: typeof adminCategoriesRoute
  adminStaffRoute: typeof adminStaffRoute
  appDashboardRoute: typeof appDashboardRoute
  appInventoryRoute: typeof appInventoryRoute
  appReportsRoute: typeof appReportsRoute
  appStockMovementsRoute: typeof appStockMovementsRoute
  authLoginRoute: typeof authLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/stock-movements': {
      id: '/(app)/stock-movements'
      path: '/stock-movements'
      fullPath: '/stock-movements'
      preLoaderRoute: typeof appStockMovementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/reports': {
      id: '/(app)/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof appReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/inventory': {
      id: '/(app)/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof appInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/dashboard': {
      id: '/(app)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/staff': {
      id: '/(admin)/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof adminStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/categories': {
      id: '/(admin)/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof adminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/branches': {
      id: '/(admin)/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof adminBranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/products': {
      id: '/(app)/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof appProductsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/products/$id': {
      id: '/(app)/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof appProductsIdRouteImport
      parentRoute: typeof appProductsRouteRoute
    }
  }
}

interface appProductsRouteRouteChildren {
  appProductsIdRoute: typeof appProductsIdRoute
}

const appProductsRouteRouteChildren: appProductsRouteRouteChildren = {
  appProductsIdRoute: appProductsIdRoute,
}

const appProductsRouteRouteWithChildren =
  appProductsRouteRoute._addFileChildren(appProductsRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appProductsRouteRoute: appProductsRouteRouteWithChildren,
  adminBranchesRoute: adminBranchesRoute,
  adminCategoriesRoute: adminCategoriesRoute,
  adminStaffRoute: adminStaffRoute,
  appDashboardRoute: appDashboardRoute,
  appInventoryRoute: appInventoryRoute,
  appReportsRoute: appReportsRoute,
  appStockMovementsRoute: appStockMovementsRoute,
  authLoginRoute: authLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
